project:
  type: website
  output-dir: docs
website:
  title: "" 
  site-url: https://melaniemml.github.io/Prof-website/
  repo-url: https://github.com/melaniemml/Prof-website
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: illustrations.qmd
        text: Illustrations

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true
    grid:
      body-width: 1000px

editor: visual

